#!/bin/bash
echo -e "\033[1;36m ESTA ES TU INFORMACION!\033[0m"
echo ""
echo -ne "TU DOMINIO NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "SU KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://sshplus.net/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m SU KEY se guarda en el archivoo /root/server.pub\033[0m"
echo -e "\033[1;33mGuárdelo en un lugar seguro, es posible que lo necesite en el futuro.!\033[0m"
echo ""
read -p "Presiona [Enter] para regresar al menú o CTRL+C para salir"
slowdns