#!/bin/bash
clear
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CORTITLE='\033[1;41m'
SCOLOR='\033[0m'
banner='
 ___ _    _____      _____  _  _ ___ 
/ __| |  / _ \ \    / /   \| \| / __|
\__ \ |_| (_) \ \/\/ /| |) | .  \__ \
|___/____\___/ \_/\_/ |___/|_|\_|___/'

echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${CORTITLE}            CLIENTE SLOWDNS          ${SCOLOR}"
echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${RED}$banner${SCOLOR}"
[[ ! -e dns ]] && {
    yes| termux-setup-storage > /dev/null 2>&1
    unset LD_PRELOAD > /dev/null 2>&1
    cd $HOME
    mv slowdns $PREFIX/bin/slowdns
    chmod +x $PREFIX/bin/slowdns
    [[ $(grep -c 'slowdns' $PREFIX/etc/profile) == '0' ]] && echo 'slowdns' >> $PREFIX/etc/profile
    echo -e "\n${GREEN}DESCARGANDO EL SCRIPT POR FAVOR ESPERE ! ${SCOLOR}"
    pkg upgrade > /dev/null 2>&1
    pkg install wget -y > /dev/null 2>&1
    wget https://raw.githubusercontent.com/arquivobgx/SSHPLUS/main/Install/dns > /dev/null 2>&1
    echo -e "\n${RED}[${YELLOW}!${RED}] ${YELLOW}SCRIPT DESCARGADO ! LA PRÓXIMA VEZ\nSOLO EJECUTE EL COMANDO ${RED}(${GREEN}slowdns${RED})\n${YELLOW}INCLUSO SI ESTÁS SIN CONEXIÓN !${SCOLOR}"
    chmod +x dns
}
[[ ! -e $HOME/credenciais ]] && {
    ns=$1
    [[ -z "$ns" ]] && {
        echo -e "\n${RED}COMANDO IMCOMPLETO${SCOLOR}"
        exit 0
    }
    chave=$2
    [[ -z "$chave" ]] && {
        echo -e "\n${RED}COMANDO IMCOMPLETO${SCOLOR}"
        exit 0
    }
    echo -e "$ns\n$chave" > $HOME/credenciais
} || {
    perg=$(echo "${SCOLOR}[s/n]: ")
    echo -e "\n${YELLOW}SCRIPT YA ESTÁ CONFIGURADO CON \nSERVIDOR YA ESTÁ LISTO PARA LA CONEXIÓN"
    read -p "$(echo -e "${GREEN}QUIERES SEGUIR CON LO MISMO?${SCOLOR} [s/n]: ")" -e -i s opc
    [[ "$opc" != @(s|sim|S|SIM) ]] && {
        rm $HOME/credenciais dns > /dev/null 2>&1
        rm $PREFIX/bin/slowdns > /dev/null 2>&1
        sed -i '/slowdns/d' $PREFIX/etc/profile > /dev/null 2>&1
        echo -e "\n${RED}SCRIPT REMOVIDO !${SCOLOR}"
        rm slowdns > /dev/null 2>&1
        exit 0
    } || {
        unset LD_PRELOAD > /dev/null 2>&1
        ns=$(sed -n 1p $HOME/credenciais)
        chave=$(sed -n 2p $HOME/credenciais)
    }
}
dns=$3
[[ -z "$dns" ]] && {
    dns='187.50.250.115'
}
echo -ne "\n${RED}[${YELLOW}!${RED}] ${YELLOW}PARA CONTINUAR, \nSO ${RED}(${YELLOW}DADOS MOVEIS${RED})\n${YELLOW}ATIVADO ${GREEN}ENTER ${YELLOW}PARA CONTINUAR.. ${SCOLOR}"; read
$HOME/dns -udp ${dns}:53 -pubkey ${chave} ${ns} 127.0.0.1:2222 > /dev/null 2>&1 &
echo -e "\n${RED}[${GREEN}âˆš${RED}]${SCOLOR} - ${GREEN}SLOWDNS INICIADO!${SCOLOR} - ${RED}[${GREEN}âˆš${RED}]\n\n${RED}[${YELLOW}!${RED}] ${YELLOW}AGORA CONECTE-SE EM UM APP VPN\nOU CLICK EM ${GREEN}ENTER ${RED}PARA DESCONECTAR ${SCOLOR}"; read
piddns=$(ps x| grep -w 'dns' | grep -v 'grep'| awk -F' ' {'print $1'})
[[ ${piddns} != '' ]] && kill ${piddns} > /dev/null 2>&1
